
server:
  port: 8084
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tcs?useSSL=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 101.37.168.55
    port: 6379
    password: wind
    jedis:
      pool:
        max-active: 66
    timeout: 1000

dubbo:
  application:
    name: case-service-provider
  registry:
    protocol: zookeeper
    address: 101.37.168.55:2181
  protocol:
    port: 20886
pagehelper:
  helper-dialect: mysql
  reasonable: true

