spring:
  redis:
    host: 101.37.168.55
    port: 6379
    password: wind
    jedis:
      pool:
        max-active: 66
    timeout: 5000
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
dubbo:
  application:
    name: web-topic
  registry:
    address: 101.37.168.55:2181
    protocol: zookeeper
server:
  port: 9095
image:
  server: http://101.37.168.55:7777/
fdfs:
  so-timeout: 3000
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 101.37.168.55:22122
