spring:
  redis:
    host: 101.37.168.55
    port: 6379
    password: wind
    jedis:
      pool:
        max-active: 66
    timeout: 10000
  thymeleaf:
    cache: false
    encoding: utf-8
  servlet:
    multipart:
      max-file-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
dubbo:
  application:
    name: web-case
  registry:
    address: 101.37.168.55:2181
    protocol: zookeeper
server:
  port: 9094
  tomcat:
    uri-encoding: UTF-8
image:
  server: http://101.37.168.55:7777/
fdfs:
  so-timeout: 3000
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 101.37.168.55:22122
